#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# run 'doctl compute region list' for a list of available regions
REGION=${REGION:-sfo2}

# name of the node
NAME=${NAME:-unifi}

SSH_KEY_NAME=${NAME:-yubikey}
# node size
SIZE=4gb

command_exists () {
    type "$1" &> /dev/null;
}

# check doctl
if ! command_exists doctl; then
    echo "Please install doctl: brew install doctl"
    exit 1
fi

SSH_ID=$(doctl compute ssh-key list | grep -i "${SSH_KEY_NAME}" | cut -d' ' -f1)
SSH_KEY=$(doctl compute ssh-key get "${SSH_ID}" --format FingerPrint --no-header)

# create tags
doctl compute tag create unifi > /dev/null

 # create the node
doctl compute droplet create "${NAME}" \
    --region "${REGION}" \
    --image ubuntu-16-04-x64 \
    --size "${SIZE}" \
    --tag-name unifi \
    --ssh-keys "${SSH_KEY}" \
    --enable-ipv6 \
    --enable-monitoring \
    --user-data-file "${DIR}/templates/unifi.sh \
    --wait

# get the public ip of the node
ID=$(doctl compute droplet list | grep "${NAME}" | cut -d' ' -f1)
PUBLIC_IP=$(doctl compute droplet get "${ID}" --format PublicIPv4 --no-header)

echo "- Waiting node to finish installation"

# wait till we copy letsencrypt.sh
while ! scp -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "${DIR}/templates/letsencrypt.sh root@"${PUBLIC_IP}":/root 2> /dev/null; do
    sleep 10
done

echo "- Creating the firewall"
doctl compute firewall create \
    --name unifi \
    --inbound-rules "protocol:tcp,ports:22,address:0.0.0.0/0,address:::/0 protocol:tcp,ports:80,address:0.0.0.0/0,address:::/0 protocol:tcp,ports:8080,address:0.0.0.0/0,address:::/0 protocol:tcp,ports:8081,address:0.0.0.0/0,address:::/0 protocol:tcp,ports:8443,address:0.0.0.0/0,address:::/0 protocol:tcp,ports:8843,address:0.0.0.0/0,address:::/0 protocol:tcp,ports:8880,address:0.0.0.0/0,address:::/0 protocol:udp,ports:3478,address:0.0.0.0/0,address:::/0" \
    --outbound-rules "protocol:icmp,address:0.0.0.0/0,address:::/0 protocol:tcp,ports:all,address:0.0.0.0/0,address:::/0 protocol:udp,ports:all,address:0.0.0.0/0,address:::/0" \
    --tag-names unifi

echo "- Installation completed"
